default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_app_development
  username: postgres
  password: suwimubanga1

test:
  <<: *default
  database: recipe_app_development
  username: postgres
  password: suwimubanga1

production:
  <<: *default
  database: recipe_app_production